### ISSUE TITLE
Could not find native library libsodium.so in jar

### ISSUE THREAD

**Issue by ffflorian** [wireapp/wire-bot-java#31]
1. Registered my bot
2. Built the bot on macOS 10.12.3 with `make` - without any errors.
3. Deployed `hello.jar`, `hello.yaml` and `keystore.jks`.
4. Started it on Debian 8 with `java -jar hello.jar server hello.yaml` - without problems.
5. Tried to start a conversation with the bot.
6. Received the error `Could not find native library libsodium.so in jar`.

Excerpt from log:
```
INFO  [2017-03-13 17:17:42,301] org.eclipse.jetty.server.Server: Started @5381ms
13/03/2017 18:17:57 - [INFO] - onNewBot: user: 9bce80c5-ec4c-457e-a966-7eecee1674d9/Florian, locale: en
ERROR [2017-03-13 17:17:57,676] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: f095cab88d2759c0
! java.io.FileNotFoundException: Could not find native library libsodium.so in jar.
! at com.wire.cryptobox.NativeLibraryLoader.loadFromJar(NativeLibraryLoader.java:28)
! ... 65 common frames omitted
! Causing: java.lang.RuntimeException: java.io.FileNotFoundException: Could not find native library libsodium.so in jar.
! at com.wire.cryptobox.NativeLibraryLoader.loadFromJar(NativeLibraryLoader.java:45)
! at com.wire.cryptobox.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:11)
! at com.wire.cryptobox.CryptoBox.<clinit>(CryptoBox.java:45)
```

**Comment by dkovacevic** [comment]
Try building by passing the correct profile flag

mvn -Plinux package
mvn -Pdarwin package 
mvn -Pwindows package

**Comment by ffflorian** [comment]
I rebuilt it with `mvn mvn -Pdarwin [package]` and I still get the same error.
